#!/usr/bin/bash -u

alias ShowPath='( IFS=:;for p in $PATH;do echo $p;done )'
AddPath () {
  # option -pre
  local pre=off
  if [[ $1 = '-pre' ]];then
    pre=on
    shift
  fi
  #
  local pstr="$PATH"
  for p in "$@";do
    if [[ ":$pstr:" != *":$p:"* ]];then
      if [[ $pre = 'on' ]];then
        pstr=".:${p}:${pstr#.:}"
      else
        pstr="${pstr}:${p}"
      fi
    fi
  done
  echo "$pstr"
}

ConvPath () {
  if [[ $1 = '-r' ]];then
    {
		cat <<-'_PERL_'
			s{^/([a-zA-Z])/}{$1:\\};   # windows drive
			s{/}{\\}g;                 # windows path
			__END__
		_PERL_
		echo "$2"
    } | perl -pl
  else
    {
		cat <<-'_PERL_'
			$_ = lcfirst;              # windows drive
			s{^([a-zA-Z]):\\}{/$1/};   # windows drive
			s{\\}{/}g;                 # windows path
			__END__
		_PERL_
		echo "$1"
    } | perl -pl
  fi
}

